-- -----------------------------------------------------------------------------
-- Estructura de tabla para comentarios en Supabase (PostgreSQL)
-- -----------------------------------------------------------------------------

CREATE TABLE comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL,
  contenido TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Habilitar Row Level Security (RLS) para que el frontend pueda interactuar
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;

-- Políticas de Seguridad
-- 1. Cualquiera puede leer los comentarios
CREATE POLICY "Comentarios son públicos" ON comments FOR SELECT USING (true);

-- 2. Solo los usuarios autenticados pueden crear sus propios comentarios
CREATE POLICY "Usuarios autenticados pueden insertar" ON comments FOR INSERT WITH CHECK (auth.uid() = user_id);

-- -----------------------------------------------------------------------------
-- Explicación de la estructura:
-- -----------------------------------------------------------------------------
-- 1. `id`: Identificador único y autoincremental de la tabla de comentarios.
-- 2. `user_id`: UUID referenciando al usuario autenticado en auth.users de Supabase.
-- 3. `contenido`: El texto del comentario.
-- 4. `created_at`: Generado automáticamente con la hora en UTC.
-- -----------------------------------------------------------------------------
